/**
 * @file main.c
 *
 *  	 Created on: Dec 13, 2020
 *      Author: Michał Pałka
 *	\n
 * 	This is the example how to use libNMEA library. It base on the code generated by cubeMX.\n
 * 	It shows how to integrate the library with hour project.\n
 * 	IT IS NOT REDY TO COMPILE FILE!\n
 *	\n
 *	This example show how to realize measurement of vechicle acceleration from 10 to 60 kmph using libNMEA features. 
 */
...
/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include "main.h"
/* USER CODE END Includes */
...
/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */


int time;	/**< is a acceleration measurement var which represents time of acceleration in seconds*/
/**
 * stop_measure_speed_CB is a callback function which ends acceleration measurement and unregister CB when speed will exceed 60 kmph.
 @code
void stop_measure_speed_CB(void){
	time = nmea_data.UTC_time - time;	//calculate acceleration time
	NMEA_CB_unregister(SPEED_RISE_BARRIER_CB);	//unregister callback
}
 @endcode
 */
void stop_measure_speed_CB(void){
	time = nmea_data.UTC_time - time;
	NMEA_CB_unregister(SPEED_RISE_BARRIER_CB);
}
/**
 * start_measure_speed_CB is a callback function which starts acceleration measurement and register stop_measure_speed_CB callback function when speed will exceed 10 kmph.
 @code
void start_measure_speed_CB(void){
	time = nmea_data.UTC_time;	//assign time of ivent to time var
	NMEA_CB_register(&stop_measure_speed_CB, SPEED_RISE_BARRIER_CB, 60);	//register stop_measure_speed_CB function
}
 @endcode
 */
void start_measure_speed_CB(void){
	time = nmea_data.UTC_time;
	NMEA_CB_register(&stop_measure_speed_CB, SPEED_RISE_BARRIER_CB, 60);
}
/* USER CODE END 0 */
...
/**
 * main function example shows how to initialize NMEA library, register callback function and how to place NMEA_process_task.
 * @code
int main(void)
{
  ...
  // USER CODE BEGIN 2 

  NMEA_init(&huart4, &hdma_uart4_rx);	//library initialization. Pass the UART and DMA handler structures
  NMEA_CB_register(&start_measure_speed_CB, SPEED_RISE_BARRIER_CB, 10);	//CB function registration

  // USER CODE END 2 

  // Infinite loop 
  // USER CODE BEGIN WHILE 
  while (1)
  {
	  NMEA_process_task();	//library process. PLACE IT IN THE MAIN LOOP! Note that you should handle the status codes.
    // USER CODE END WHILE 

    // USER CODE BEGIN 3 
  }
  // USER CODE END 3 
}
 * @endcode
 */
int main(void)
{
  ...
  /* USER CODE BEGIN 2 */

  NMEA_init(&huart4, &hdma_uart4_rx);	/*library initialization. Pass the UART and DMA handler structures*/
  NMEA_CB_register(&start_measure_speed_CB, SPEED_RISE_BARRIER_CB, 10);	/*CB function registration*/

  /* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
	  NMEA_process_task();	/*library process. PLACE IT IN THE MAIN LOOP! Note that you should handle the status codes.*/
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
  }
  /* USER CODE END 3 */
}
...

